Whitespace cleanup

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,19 +1,19 @@
 #!/bin/sh -eu
 if [ "$#" -eq 1 ]; then
-	dumb_init_bin=$(readlink -f "$1")
+    dumb_init_bin=$(readlink -f "$1")
 else
-	dumb_init_bin=$(which dumb-init) || {
-		echo "Couldn't find dumb-init on your path, exiting."
-		exit 1
-	}
+    dumb_init_bin=$(which dumb-init) || {
+        echo "Couldn't find dumb-init on your path, exiting."
+        exit 1
+    }
 fi
 
 echo "Running with dumb-init at '$dumb_init_bin'"
 
 run_tests() {
-	./test-proxies-signals "$dumb_init_bin"
-	./test-exit-status "$dumb_init_bin"
-	./test-help-message "$dumb_init_bin"
+    ./test-proxies-signals "$dumb_init_bin"
+    ./test-exit-status "$dumb_init_bin"
+    ./test-help-message "$dumb_init_bin"
 }
 
 cd tests
diff --git a/tests/test-exit-status b/tests/test-exit-status
--- a/tests/test-exit-status
+++ b/tests/test-exit-status
@@ -3,10 +3,10 @@ dumb_init="$1"
 
 # dumb-init should exit with the same exit status as the process it launches.
 for i in $(seq 0 255); do
-	status=$($dumb_init sh -c "exit $i"; echo $?)
+    status=$($dumb_init sh -c "exit $i"; echo $?)
 
-	if [ "$status" -ne "$i" ]; then
-		echo "Error: Expected exit status $i, got $status."
-		exit 1
-	fi
+    if [ "$status" -ne "$i" ]; then
+        echo "Error: Expected exit status $i, got $status."
+        exit 1
+    fi
 done
diff --git a/tests/test-help-message b/tests/test-help-message
--- a/tests/test-help-message
+++ b/tests/test-help-message
@@ -7,14 +7,14 @@ dumb_init="$1"
 status=$($dumb_init > /dev/null 2>&1; echo $?)
 
 if [ "$status" -ne 0 ]; then
-	msg=$($dumb_init 2>&1 || true)
-	msg_len=${#msg}
+    msg=$($dumb_init 2>&1 || true)
+    msg_len=${#msg}
 
-	if [ "$msg_len" -le 50 ]; then
-		echo "Error: Expected dumb-init with no arguments to print a useful message, but it was only ${msg_len} chars long."
-		exit 1
-	fi
+    if [ "$msg_len" -le 50 ]; then
+        echo "Error: Expected dumb-init with no arguments to print a useful message, but it was only ${msg_len} chars long."
+        exit 1
+    fi
 else
-	echo "Error: Expected dumb-init with no arguments to return nonzero, but it returned ${status}."
-	exit 1
+    echo "Error: Expected dumb-init with no arguments to return nonzero, but it returned ${status}."
+    exit 1
 fi
diff --git a/tests/test-proxies-signals b/tests/test-proxies-signals
--- a/tests/test-proxies-signals
+++ b/tests/test-proxies-signals
@@ -19,20 +19,20 @@ pid="$!"
 $read_cmd > /dev/null
 
 for expected in $(catchable_signals); do
-	kill -s "$expected" "$pid"
-	echo -n "Sent signal ${expected}... "
-	received=$($read_cmd) || {
-		echo
-		echo "Error: Didn't receive signal within 1 second."
-		exit 1
-	}
+    kill -s "$expected" "$pid"
+    echo -n "Sent signal ${expected}... "
+    received=$($read_cmd) || {
+        echo
+        echo "Error: Didn't receive signal within 1 second."
+        exit 1
+    }
 
-	echo "received signal ${received}."
+    echo "received signal ${received}."
 
-	if [ "$expected" -ne "$received" ]; then
-		echo "Error: Received signal $received, but expected signal $expected."
-		exit 1
-	fi
+    if [ "$expected" -ne "$received" ]; then
+        echo "Error: Received signal $received, but expected signal $expected."
+        exit 1
+    fi
 done
 
 # Turn off job monitoring so we don't get a spurious "[1] + Killed" printed
